# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBasicRunthrough():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_basicRunthrough(self):
    self.driver.get("https://192.168.1.11:5000/login")
    self.driver.find_element(By.LINK_TEXT, "Register").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("selenium")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("password")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("selenium@email.com")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(8)").click()
    self.driver.find_element(By.LINK_TEXT, "Forgot Password").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("selenium@email.com")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(4)").click()
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("selenium")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("reset")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(6)").click()
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > td:nth-child(2)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > td:nth-child(2)").text == "selenium@email.com"
    self.driver.find_element(By.LINK_TEXT, "Network Account").click()
    self.driver.find_element(By.CSS_SELECTOR, "input").click()
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3)").text == "Status: PENDING"
    self.driver.find_element(By.CSS_SELECTOR, ".content").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("root")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(6)").click()
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) > td:nth-child(2)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) > td:nth-child(2)").text == "1"
    self.driver.find_element(By.LINK_TEXT, "Network Account").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) > td:nth-child(2)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) > td:nth-child(2)").text == "selenium"
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) > td:nth-child(3)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) > td:nth-child(3)").text == "PENDING"
    self.driver.find_element(By.CSS_SELECTOR, "html").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) > td:nth-child(4) button").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) > td:nth-child(3)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) > td:nth-child(3)").text == "APPROVED"
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) > td:nth-child(5) button").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) > td:nth-child(3)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) > td:nth-child(3)").text == "DENIED"
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("selenium")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("reset")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(6)").click()
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.LINK_TEXT, "Network Account").click()
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3)").text == "Status: DENIED"
    self.driver.find_element(By.CSS_SELECTOR, "html").click()
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("reset")
    self.driver.find_element(By.ID, "repassword").click()
    self.driver.find_element(By.ID, "repassword").send_keys("reset")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(5)").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("root")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(6)").click()
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.LINK_TEXT, "Network Account").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
  
